server:
  # 8004表示注册到zookeeper服务器的支付服务提供者端口号
  port: 8004
spring:
  cloud:
    zookeeper:
      # 默认localhost:2181
      connect-string: 192.168.91.128:2181
  application:
    name: cloud-provider-payment

